win_build_task:
  env:
    matrix:
      - {
          GENERATOR_STRING: "Visual Studio 15 2017 Win64",
          WIN_API_VERSION: 7.1,
        }
      - { GENERATOR_STRING: "Visual Studio 15 2017", WIN_API_VERSION: 7.1 }
      - {
          GENERATOR_STRING: "Visual Studio 15 2017 Win64",
          WIN_API_VERSION: 8.1,
        }
      - { GENERATOR_STRING: "Visual Studio 15 2017", WIN_API_VERSION: 8.1 }
      - { GENERATOR_STRING: "Visual Studio 15 2017 Win64", WIN_API_VERSION: 10 }
      - { GENERATOR_STRING: "Visual Studio 15 2017", WIN_API_VERSION: 10 }

  windows_container:
    dockerfile: .ci/Dockerfile
    os_version: 2019

  build_script:
    - mkdir __build && cd __build
    - cmake -G "%GENERATOR_STRING%" ..
    - cmake --build .

  package_artifacts:
    path: __build/Debug/*
